version: '3.9'

services:
#  vk-affinity-postgresql:
#    image: postgres:16.0-alpine3.18
#    ports: [ '8032:5432' ]
#    environment:
#      POSTGRES_USER: darling_postgresql
#      POSTGRES_PASSWORD: darling_password
#      POSTGRES_DB: vk
  server:
    build:
      context: .
    networks:
      - metrics_network
  vk-affinity-prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus/:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - metrics_network

networks:
  metrics_network: