global:
  scrape_interval: 15s
  evaluation_interval: 5s

scrape_configs:
  - job_name: vk-affinity-metrics
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ server:3032 ]